### PR TITLE
initial update

### PR DESCRIPTION
**Pull request by jobisoft**
This is the first step to get it installed in TB68. To test it, you can get release candidates of TB68 here:
https://ftp.mozilla.org/pub/thunderbird/candidates/68.0-candidates/

I have no idea, what this addon does and where to look and if it actually works. I looked at the JS code and did not see anything that needs an update, but since you overlay stuff, some of the overlayed files could have changed.

If you tell me what I need to click to trigger an action of this add-on - or better - what does not work as expected, I could go on.

You can of course just merge this now and have a look for yourself. As you wish.

### CODE REVIEW

**Comment by jobisoft** [comment]
Here the zip file ready to be installed in TB68, if you do not want to checkout the pull request before testing it.

[AutoSaveDraftsFolders.zip](https://github.com/dlech/AutoSaveDraftsFolders/files/3496462/AutoSaveDraftsFolders.zip)

**Comment by dlech** [comment]
Thanks for the pull request. I've spent several hours trying to get it to work, but it seems like the xul overlays are not loading. I can't find any useful messages in Error Console or Developer Toolbox. There are a few messages that I can tell that the extension is loading, but inspecting the xul shows nothing from this extension.

**Comment by dlech** [comment]
I came back to this again and found that the scripts are actually running even though they are not visible in xul. However, the main overlay for `am-copies.xul` is not loading. (I dropped the `Overlay` from the name in `chrome.mainifest`. I have a hunch that this is not working because `am-copies.xul` is loaded as an iframe and not a main window.

**Comment by dlech** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1574823

**Comment by jobisoft** [comment]
So it looks like your add-on hit indeed a bug in Thunderbird. We will have to wait and see.

**Comment by jobisoft** [comment]
The bug has been fixed in TB, does it work now?

**Comment by dlech** [comment]
The fix did not make it into TB68, but is marked for TB68.1.

**Comment by dlech** [comment]
Had to make a few more changes, but the addon seem to be working now.

**Comment by jobisoft** [comment]
Nice. Sorry that I did not get back to you, but I am currently packed with work.

**Pull request merged**
